using System.Text;
using KryossApi.Data.Entities;

namespace KryossApi.Services.Reports;

public static class ReportHelpers
{
    public static string GetGrade(decimal score) => score switch
    {
        >= 97 => "A+",
        >= 93 => "A",
        >= 90 => "A-",
        >= 87 => "B+",
        >= 83 => "B",
        >= 80 => "B-",
        >= 77 => "C+",
        >= 73 => "C",
        >= 70 => "C-",
        >= 67 => "D+",
        >= 63 => "D",
        >= 60 => "D-",
        _ => "F"
    };

    public static string TruncateCpu(string? cpuName)
    {
        if (cpuName == null) return "N/A";
        var name = cpuName.Replace("(R)", "").Replace("(TM)", "").Replace("CPU ", "").Trim();
        return name.Length > 30 ? name[..27] + "..." : name;
    }

    public static void AppendRibbonSvg(StringBuilder sb)
    {
        sb.AppendLine($"<img class='cover-ribbon' src='{RibbonData.DataUri}' alt='' />");
    }

    /// <summary>
    /// eyebrow defaults to brand.CompanyName when null.
    /// </summary>
    public static void AppendPageHeader(StringBuilder sb, string title, ReportBranding brand, string? eyebrow = null)
    {
        var effectiveEyebrow = eyebrow ?? brand.CompanyName;
        sb.AppendLine("<div class='ph'>");
        sb.AppendLine("<div class='ph-text'>");
        sb.AppendLine($"<div class='ph-eyebrow'>{HtmlEncode(effectiveEyebrow.ToUpperInvariant())}</div>");
        sb.AppendLine($"<h1>{HtmlEncode(title)}</h1>");
        sb.AppendLine("</div>");
        if (brand.LogoUrl is not null)
            sb.AppendLine($"<img src='{HtmlEncode(brand.LogoUrl)}' alt=''>");
        sb.AppendLine("</div>");
        sb.AppendLine("<div class='stripe'></div>");
    }

    public static void AppendFooter(StringBuilder sb, ReportBranding brand, string detail, ReportUserInfo? user = null)
    {
        sb.AppendLine("<div class='footer'>");
        if (user is not null)
        {
            var fullName = string.IsNullOrWhiteSpace(user.FullName) ? "—" : user.FullName!;
            var email    = string.IsNullOrWhiteSpace(user.Email)    ? "—" : user.Email!;
            var phone    = string.IsNullOrWhiteSpace(user.Phone)    ? "—" : user.Phone!;
            var job      = string.IsNullOrWhiteSpace(user.JobTitle) ? ""  : $" &middot; {HtmlEncode(user.JobTitle)}";
            sb.AppendLine($"<p><strong>Prepared by: {HtmlEncode(fullName)}</strong>{job}</p>");
            sb.AppendLine($"<p>{HtmlEncode(email)} &middot; {HtmlEncode(phone)}</p>");
        }
        sb.AppendLine($"<p>Generated by {HtmlEncode(brand.CompanyName)} &mdash; Your Technology Advisor</p>");
        sb.AppendLine($"<p>{DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC &bull; {detail}</p>");
        sb.AppendLine("</div>");
    }

    public static void AppendHtmlHead(StringBuilder sb, string title, ReportBranding brand, bool isOrgReport,
        string htmlLang = "en", ReportUserInfo? user = null, string? detail = null)
    {
        sb.AppendLine($"<!DOCTYPE html><html lang='{HtmlEncode(htmlLang)}'><head><meta charset='UTF-8'>");
        sb.AppendLine("<meta name='viewport' content='width=device-width, initial-scale=1.0'>");
        sb.AppendLine($"<title>{HtmlEncode(title)}</title>");
        sb.AppendLine("<link href='https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;900&display=swap' rel='stylesheet'>");
        sb.AppendLine("<style>");
        sb.AppendLine(isOrgReport ? ReportStyles.GetOrgReportStyles(brand) : ReportStyles.GetReportStyles(brand));
        // A4 print discipline layered AFTER the base styles
        sb.AppendLine(ReportStyles.GetA4PrintCss(brand));
        // Running footer on every .page
        if (user is not null)
        {
            AppendRunningFooterCss(sb, user, detail);
        }
        sb.AppendLine("</style></head><body>");
    }

    /// <summary>
    /// Emits a CSS rule that injects a running footer strip on every `.page`
    /// via `::after`. Works on screen AND print — no JavaScript required.
    /// </summary>
    public static void AppendRunningFooterCss(StringBuilder sb, ReportUserInfo user, string? detail)
    {
        static string CssEscape(string? s)
        {
            if (string.IsNullOrEmpty(s)) return "—";
            return s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", " ").Replace("\r", "");
        }

        var fullName = CssEscape(user.FullName);
        var email    = CssEscape(user.Email);
        var phone    = CssEscape(user.Phone);
        var jobTitle = string.IsNullOrWhiteSpace(user.JobTitle) ? "" : " · " + CssEscape(user.JobTitle);
        var detailStr = CssEscape(detail ?? "");
        var ts       = DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm");

        var line1 = $"Prepared by {fullName}{jobTitle}  ·  {email}  ·  {phone}";
        var line2 = $"Generated {ts} UTC  ·  {detailStr}";

        sb.AppendLine(".page { position: relative !important; }");
        sb.AppendLine(".page::after {");
        sb.AppendLine($"    content: \"{line1}\\A {line2}\";");
        sb.AppendLine("    white-space: pre;");
        sb.AppendLine("    position: absolute;");
        sb.AppendLine("    left: 0;");
        sb.AppendLine("    right: 0;");
        sb.AppendLine("    bottom: 0;");
        sb.AppendLine("    padding: 3mm 12mm 4mm;");
        sb.AppendLine("    font-family: 'Montserrat', 'Verdana', sans-serif;");
        sb.AppendLine("    font-size: 7.5pt;");
        sb.AppendLine("    line-height: 1.45;");
        sb.AppendLine("    color: #666;");
        sb.AppendLine("    background: #fafafa;");
        sb.AppendLine("    border-top: 0.5pt solid #e5e7eb;");
        sb.AppendLine("    text-align: center;");
        sb.AppendLine("    z-index: 10;");
        sb.AppendLine("}");
        sb.AppendLine(".onepager::after { content: none !important; display: none !important; }");
        sb.AppendLine(".page .pb { padding-bottom: 18mm !important; }");
    }

    public static void AppendOnePagerFooter(StringBuilder sb, ReportUserInfo user, Organization org, string lang)
    {
        var fullName = string.IsNullOrWhiteSpace(user.FullName) ? "—" : user.FullName!;
        var email    = string.IsNullOrWhiteSpace(user.Email)    ? "—" : user.Email!;
        var phone    = string.IsNullOrWhiteSpace(user.Phone)    ? "—" : user.Phone!;
        var job      = string.IsNullOrWhiteSpace(user.JobTitle) ? ""  : $" · {user.JobTitle}";

        sb.AppendLine("<div class='op-footer'>");
        sb.AppendLine("<div class='op-footer-row'>");
        sb.AppendLine("<div>");
        sb.AppendLine($"<div class='op-footer-user'>{HtmlEncode(T("op.footer.prepared", lang))}: {HtmlEncode(fullName)}{HtmlEncode(job)}</div>");
        sb.AppendLine($"<div>{HtmlEncode(email)} &middot; {HtmlEncode(phone)}</div>");
        sb.AppendLine("</div>");
        sb.AppendLine("<div class='op-footer-brand'>");
        sb.AppendLine($"<div>{HtmlEncode(T("op.footer.confidential", lang))} {HtmlEncode(org.Name)}</div>");
        sb.AppendLine($"<div>{HtmlEncode(T("op.footer.generated", lang))} {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC</div>");
        sb.AppendLine("</div>");
        sb.AppendLine("</div></div>");
    }

    public static void AppendFrameworkBars(StringBuilder sb, List<FrameworkScoreDto> frameworkScores)
    {
        sb.AppendLine("<div class='framework-bars'>");
        foreach (var fs in frameworkScores)
        {
            var barColor = fs.Score >= 80 ? "#006536" : fs.Score >= 60 ? "#D97706" : "#C0392B";
            sb.AppendLine("<div class='fw-bar-row'>");
            sb.AppendLine($"<span class='fw-label'>{HtmlEncode(fs.Code)}</span>");
            sb.AppendLine($"<div class='fw-track'><div class='fw-fill' style='width:{fs.Score}%;background:{barColor}'></div></div>");
            sb.AppendLine($"<span class='fw-pct'>{fs.Score}%</span>");
            sb.AppendLine($"<span class='fw-detail'>({fs.PassCount}P / {fs.FailCount}F)</span>");
            sb.AppendLine("</div>");
        }
        sb.AppendLine("</div>");
    }

    /// <summary>
    /// Renders framework compliance bars with P/F counts normalized to
    /// per-machine averages. Use in ORG-level reports where raw counts are sums over all runs.
    /// </summary>
    public static void AppendNormalizedFrameworkBars(StringBuilder sb,
        List<FrameworkScoreDto> frameworkScores, int machineCount, string? caption = null)
    {
        var normalized = machineCount > 0
            ? frameworkScores.Select(fs => new FrameworkScoreDto
            {
                Code      = fs.Code,
                Name      = fs.Name,
                Score     = fs.Score,
                PassCount = (short)Math.Round((double)fs.PassCount / machineCount),
                FailCount = (short)Math.Round((double)fs.FailCount / machineCount)
            }).ToList()
            : frameworkScores;

        AppendFrameworkBars(sb, normalized);
        if (!string.IsNullOrEmpty(caption))
        {
            sb.AppendLine($"<p style='font-size:10px;color:#888;margin:4px 0 12px;text-align:right;font-style:italic'>{HtmlEncode(caption)}</p>");
        }
    }

    public static void AppendMachineHardwareSection(StringBuilder sb, Machine machine)
    {
        sb.AppendLine("<h3>Hardware &amp; Security</h3>");
        sb.AppendLine("<div class='hw-grid'>");

        sb.AppendLine("<div class='hw-col'>");
        sb.AppendLine("<h4>Hardware</h4>");
        sb.AppendLine("<table class='info-table'>");
        sb.AppendLine($"<tr><td>Manufacturer</td><td>{HtmlEncode(machine.Manufacturer ?? "N/A")}</td></tr>");
        sb.AppendLine($"<tr><td>Model</td><td>{HtmlEncode(machine.Model ?? "N/A")}</td></tr>");
        sb.AppendLine($"<tr><td>Serial</td><td>{HtmlEncode(machine.SerialNumber ?? "N/A")}</td></tr>");
        sb.AppendLine($"<tr><td>Disk</td><td>{HtmlEncode(machine.DiskType ?? "N/A")} {machine.DiskSizeGb ?? 0} GB ({machine.DiskFreeGb ?? 0:F1} GB free)</td></tr>");
        sb.AppendLine("</table></div>");

        sb.AppendLine("<div class='hw-col'>");
        sb.AppendLine("<h4>Security</h4>");
        sb.AppendLine("<table class='info-table'>");
        sb.AppendLine($"<tr><td>TPM</td><td>{(machine.TpmPresent == true ? $"Yes ({HtmlEncode(machine.TpmVersion ?? "unknown")})" : "No")}</td></tr>");
        sb.AppendLine($"<tr><td>Secure Boot</td><td>{(machine.SecureBoot == true ? "Enabled" : "Disabled")}</td></tr>");
        sb.AppendLine($"<tr><td>BitLocker</td><td>{(machine.Bitlocker == true ? "Enabled" : "Disabled")}</td></tr>");
        sb.AppendLine("</table></div>");

        sb.AppendLine("<div class='hw-col'>");
        sb.AppendLine("<h4>Network</h4>");
        sb.AppendLine("<table class='info-table'>");
        sb.AppendLine($"<tr><td>IP Address</td><td>{HtmlEncode(machine.IpAddress ?? "N/A")}</td></tr>");
        sb.AppendLine($"<tr><td>MAC Address</td><td>{HtmlEncode(machine.MacAddress ?? "N/A")}</td></tr>");
        sb.AppendLine($"<tr><td>Domain</td><td>{HtmlEncode(machine.DomainStatus ?? "N/A")} {(machine.DomainName != null ? $"({HtmlEncode(machine.DomainName)})" : "")}</td></tr>");
        sb.AppendLine("</table></div>");

        sb.AppendLine("</div>");
    }

    public static void AppendHygieneSummary(StringBuilder sb, HygieneScanDto hygiene)
    {
        sb.AppendLine($"<p class='cat-summary'>Last scan: {hygiene.ScannedAt:MMMM dd, yyyy} &mdash; {hygiene.TotalMachines} machines, {hygiene.TotalUsers} users in directory</p>");

        sb.AppendLine("<div class='summary-grid'>");
        sb.AppendLine($"<div class='stat'><span class='stat-value'>{hygiene.TotalMachines}</span><span class='stat-label'>Total AD Machines</span></div>");
        sb.AppendLine($"<div class='stat'><span class='stat-value'>{hygiene.TotalUsers}</span><span class='stat-label'>Total AD Users</span></div>");
        sb.AppendLine($"<div class='stat {(hygiene.DormantMachines > 0 ? "fail-stat" : "")}'><span class='stat-value'>{hygiene.DormantMachines}</span><span class='stat-label'>Dormant Machines</span></div>");
        sb.AppendLine($"<div class='stat {(hygiene.DormantUsers > 0 ? "fail-stat" : "")}'><span class='stat-value'>{hygiene.DormantUsers}</span><span class='stat-label'>Dormant Users</span></div>");
        sb.AppendLine("</div>");

        sb.AppendLine("<div class='summary-grid'>");
        sb.AppendLine($"<div class='stat {(hygiene.StaleMachines > 0 ? "warn-stat" : "")}'><span class='stat-value'>{hygiene.StaleMachines}</span><span class='stat-label'>Stale Machines</span></div>");
        sb.AppendLine($"<div class='stat {(hygiene.StaleUsers > 0 ? "warn-stat" : "")}'><span class='stat-value'>{hygiene.StaleUsers}</span><span class='stat-label'>Stale Users</span></div>");
        sb.AppendLine($"<div class='stat {(hygiene.PwdNeverExpire > 0 ? "warn-stat" : "")}'><span class='stat-value'>{hygiene.PwdNeverExpire}</span><span class='stat-label'>Password Never Expires</span></div>");
        sb.AppendLine($"<div class='stat {(hygiene.DisabledUsers > 0 ? "warn-stat" : "")}'><span class='stat-value'>{hygiene.DisabledUsers}</span><span class='stat-label'>Disabled Users</span></div>");
        sb.AppendLine("</div>");
    }

    public static void AppendDiskTable(StringBuilder sb, List<MachineDisk> disks)
    {
        sb.AppendLine("<table class='results-table'>");
        sb.AppendLine("<tr><th>Drive</th><th>Label</th><th>Type</th><th>Size</th><th>Free</th><th>FS</th><th>Usage</th></tr>");
        foreach (var d in disks)
        {
            var usedPct = d.TotalGb > 0 ? Math.Round((1.0 - (double)(d.FreeGb ?? 0) / d.TotalGb.Value) * 100) : 0;
            var rowClass = usedPct > 90 ? "fail" : usedPct > 75 ? "warn" : "pass";
            sb.AppendLine($"<tr class='{rowClass}'>");
            sb.AppendLine($"<td><strong>{HtmlEncode(d.DriveLetter)}</strong></td>");
            sb.AppendLine($"<td>{HtmlEncode(d.Label ?? "\u2014")}</td>");
            sb.AppendLine($"<td>{HtmlEncode(d.DiskType ?? "N/A")}</td>");
            sb.AppendLine($"<td class='num'>{d.TotalGb ?? 0} GB</td>");
            sb.AppendLine($"<td class='num'>{d.FreeGb ?? 0:F1} GB</td>");
            sb.AppendLine($"<td>{HtmlEncode(d.FileSystem ?? "N/A")}</td>");
            sb.AppendLine($"<td class='num'><strong>{usedPct:F0}%</strong></td>");
            sb.AppendLine("</tr>");
        }
        sb.AppendLine("</table>");
    }

    public static void AppendPortTable(StringBuilder sb, List<MachinePort> ports)
    {
        sb.AppendLine("<table class='results-table'>");
        sb.AppendLine("<tr><th>Port</th><th>Protocol</th><th>Status</th><th>Service</th><th>Risk</th></tr>");
        foreach (var p in ports.Take(30))
        {
            var rowClass = p.Risk != null ? "fail" : "pass";
            sb.AppendLine($"<tr class='{rowClass}'>");
            sb.AppendLine($"<td>{p.Port}</td>");
            sb.AppendLine($"<td>{HtmlEncode(p.Protocol)}</td>");
            sb.AppendLine($"<td>{HtmlEncode(p.Status)}</td>");
            sb.AppendLine($"<td>{HtmlEncode(p.Service ?? "\u2014")}</td>");
            sb.AppendLine($"<td>{(p.Risk != null ? $"<span class='severity high'>{HtmlEncode(p.Risk)}</span>" : "<span class='severity low'>OK</span>")}</td>");
            sb.AppendLine("</tr>");
        }
        sb.AppendLine("</table>");
        if (ports.Count > 30)
            sb.AppendLine($"<p class='cat-summary'>Showing 30 of {ports.Count} ports.</p>");
    }

    public static void AppendThreatTable(StringBuilder sb, List<MachineThreat> threats)
    {
        sb.AppendLine("<table class='results-table'>");
        sb.AppendLine("<tr><th>Threat</th><th>Category</th><th>Severity</th><th>Vector</th><th>Detail</th></tr>");
        foreach (var t in threats.Take(20))
        {
            sb.AppendLine("<tr class='fail'>");
            sb.AppendLine($"<td><strong>{HtmlEncode(t.ThreatName)}</strong></td>");
            sb.AppendLine($"<td>{HtmlEncode(t.Category)}</td>");
            sb.AppendLine($"<td><span class='severity {HtmlEncode(t.Severity)}'>{HtmlEncode(t.Severity)}</span></td>");
            sb.AppendLine($"<td>{HtmlEncode(t.Vector)}</td>");
            sb.AppendLine($"<td>{HtmlEncode(t.Detail ?? "\u2014")}</td>");
            sb.AppendLine("</tr>");
        }
        sb.AppendLine("</table>");
        if (threats.Count > 20)
            sb.AppendLine($"<p class='cat-summary'>Showing 20 of {threats.Count} threats.</p>");
    }

    // ── Technical Level helpers ──────────────────────────────────────────

    /// <summary>
    /// Renders the Technical Level Block 1 Asset Matrix: one row per machine,
    /// ordered worst-to-best by individual score. Paginates every ~25 rows.
    /// </summary>
    public static void AppendAssetMatrix(StringBuilder sb, List<AssessmentRun> runs, ReportBranding brand, string lang)
    {
        var es = lang == "es";

        var sorted = runs
            .OrderBy(r => r.GlobalScore ?? 100m)
            .ThenBy(r => r.Machine.Hostname)
            .ToList();

        const int perPage = 25;
        var total = sorted.Count;
        for (int offset = 0; offset < total; offset += perPage)
        {
            if (offset > 0)
            {
                sb.AppendLine("</div></div>");
                sb.AppendLine("<div class='page'>");
                AppendPageHeader(sb, es ? "Matriz de Activos (continuación)" : "Asset Matrix (continued)", brand,
                    es ? "NIVEL TÉCNICO" : "TECHNICAL LEVEL");
                sb.AppendLine("<div class='pb'>");
            }
            sb.AppendLine("<table class='results-table' style='font-size:10px'>");
            sb.AppendLine($"<tr><th style='width:28%'>{HtmlEncode(es ? "Hostname" : "Hostname")}</th><th style='width:20%'>{HtmlEncode(es ? "SO" : "OS Status")}</th><th style='width:14%' class='num'>{HtmlEncode(es ? "Críticos" : "Critical")}</th><th style='width:18%'>{HtmlEncode(es ? "Heartbeat" : "Heartbeat")}</th><th style='width:20%' class='num'>{HtmlEncode(es ? "Score" : "Score")}</th></tr>");

            foreach (var r in sorted.Skip(offset).Take(perPage))
            {
                var m = r.Machine;
                var osLabel = m.OsName ?? "—";
                var osClass = (m.OsName?.Contains("2008") == true || m.OsName?.Contains("2003") == true ||
                               m.OsName?.Contains("Windows 7") == true || m.OsName?.Contains("Vista") == true)
                    ? "fail" : "";
                var heartbeat = m.LastSeenAt.HasValue
                    ? DescribeHeartbeat(DateTime.UtcNow - m.LastSeenAt.Value, es)
                    : (es ? "nunca" : "never");
                var heartbeatDays = m.LastSeenAt.HasValue
                    ? (DateTime.UtcNow - m.LastSeenAt.Value).TotalDays
                    : 999;
                var hbClass = heartbeatDays > 7 ? "fail" : heartbeatDays > 3 ? "warn" : "";
                var score = r.GlobalScore ?? 0;
                var scoreClass = score < 60 ? "fail" : score < 85 ? "warn" : "pass";

                sb.AppendLine($"<tr class='{scoreClass}'>");
                sb.AppendLine($"<td style='font-family:monospace;font-weight:600'>{HtmlEncode(m.Hostname)}</td>");
                sb.AppendLine($"<td class='{osClass}'>{HtmlEncode(osLabel)}</td>");
                sb.AppendLine($"<td class='num'>{(r.FailCount ?? 0)}</td>");
                sb.AppendLine($"<td class='{hbClass}'>{HtmlEncode(heartbeat)}</td>");
                sb.AppendLine($"<td class='num'><strong>{score:0.#}</strong></td>");
                sb.AppendLine("</tr>");
            }
            sb.AppendLine("</table>");
        }
    }

    public static string DescribeHeartbeat(TimeSpan ago, bool es)
    {
        if (ago.TotalHours < 1) return es ? "hace minutos" : "minutes ago";
        if (ago.TotalHours < 24) return es ? $"hace {(int)ago.TotalHours}h" : $"{(int)ago.TotalHours}h ago";
        var days = (int)ago.TotalDays;
        return es ? $"hace {days} días" : $"{days} days ago";
    }

    /// <summary>
    /// Renders the Technical Level Block 2 Top 10 Critical Findings across the fleet.
    /// </summary>
    public static void AppendTop10CriticalFindings(StringBuilder sb, List<OrgControlResult> allResults, string lang)
    {
        var es = lang == "es";

        var top = allResults
            .Where(r => r.Status == "fail" && (r.Severity == "critical" || r.Severity == "high"))
            .GroupBy(r => r.ControlId)
            .Select(g => new
            {
                ControlId = g.Key,
                Name = g.First().Name,
                Severity = g.First().Severity,
                Remediation = g.First().Remediation,
                MachineCount = g.Select(x => x.RunId).Distinct().Count()
            })
            .OrderByDescending(x => x.Severity == "critical" ? 1 : 0)
            .ThenByDescending(x => x.MachineCount)
            .Take(10)
            .ToList();

        sb.AppendLine($"<h3>{HtmlEncode(es ? "Top 10 Hallazgos Críticos" : "Top 10 Critical Findings")}</h3>");

        if (top.Count == 0)
        {
            sb.AppendLine($"<p style='color:#64748B;font-size:11px'>{HtmlEncode(es ? "No se detectaron hallazgos críticos o altos en este período." : "No critical or high-severity findings detected in this period.")}</p>");
            return;
        }

        sb.AppendLine("<table class='results-table' style='font-size:10px'>");
        sb.AppendLine($"<tr><th style='width:6%'>#</th><th style='width:32%'>{HtmlEncode(es ? "Hallazgo" : "Finding")}</th><th style='width:10%'>{HtmlEncode(es ? "Sev" : "Sev")}</th><th style='width:10%' class='num'>{HtmlEncode(es ? "Equipos" : "Hosts")}</th><th>{HtmlEncode(es ? "Remediación" : "Fix")}</th></tr>");
        int n = 1;
        foreach (var t in top)
        {
            var sev = t.Severity == "critical"
                ? (es ? "CRÍTICO" : "CRITICAL")
                : (es ? "ALTO"    : "HIGH");
            var sevCls = t.Severity == "critical" ? "critical" : "high";
            sb.AppendLine("<tr class='fail'>");
            sb.AppendLine($"<td class='num'>{n++}</td>");
            sb.AppendLine($"<td><strong>{HtmlEncode(t.Name)}</strong></td>");
            sb.AppendLine($"<td><span class='severity {sevCls}'>{HtmlEncode(sev)}</span></td>");
            sb.AppendLine($"<td class='num'>{t.MachineCount}</td>");
            sb.AppendLine($"<td style='font-size:9px'>{HtmlEncode(t.Remediation ?? (es ? "(sin remediación documentada)" : "(no remediation documented)"))}</td>");
            sb.AppendLine("</tr>");
        }
        sb.AppendLine("</table>");
    }

    /// <summary>
    /// Renders the Technical Level Block 3 "Los 6 de Hierro" — 6 thematic
    /// sub-lists of hygiene failures.
    /// </summary>
    public static void AppendSixIronsHardeningAudit(StringBuilder sb, List<AssessmentRun> runs,
        List<OrgControlResult> allResults, HygieneScanDto? hygiene, string lang)
    {
        var es = lang == "es";

        sb.AppendLine($"<h3>{HtmlEncode(es ? "Los 6 de Hierro — Auditoría de Hardening" : "The 6 Irons — Hardening Audit")}</h3>");

        // 1. Cifrado — machines without BitLocker
        var noBitlocker = runs.Where(r => r.Machine.Bitlocker != true).Select(r => r.Machine.Hostname).ToList();
        AppendIronSection(sb, "🔒", es ? "Cifrado — sin BitLocker" : "Encryption — without BitLocker",
            noBitlocker, es);

        // 2. Protocolos — SMBv1 / NTLMv1 enabled
        var runLookup = runs.ToDictionary(r => r.Id, r => r.Machine.Hostname);
        var legacyProto = allResults
            .Where(r => r.Status == "fail" && (
                r.Name.Contains("SMBv1", StringComparison.OrdinalIgnoreCase) ||
                r.Name.Contains("SMB1",  StringComparison.OrdinalIgnoreCase) ||
                r.Name.Contains("NTLMv1", StringComparison.OrdinalIgnoreCase)))
            .Select(r => runLookup.GetValueOrDefault(r.RunId, "unknown"))
            .Distinct()
            .ToList();
        AppendIronSection(sb, "📡", es ? "Protocolos — SMBv1 / NTLMv1 habilitado" : "Protocols — SMBv1 / NTLMv1 enabled",
            legacyProto, es);

        // 3. Hardware — no TPM or TPM disabled
        var noTpm = runs.Where(r => r.Machine.TpmPresent != true).Select(r => r.Machine.Hostname).ToList();
        AppendIronSection(sb, "💾", es ? "Hardware — sin TPM o deshabilitado" : "Hardware — no TPM or disabled",
            noTpm, es);

        // 4. Identidad — no LAPS deployed
        var noLapsHosts = hygiene?.Findings
            .Where(f => f.Status == "NoLAPS")
            .Select(f => f.Name)
            .ToList() ?? new List<string>();
        AppendIronSection(sb, "🔑", es ? "Identidad — sin LAPS" : "Identity — no LAPS",
            noLapsHosts, es);

        // 5. Higiene — Password Never Expires accounts (count, not hostnames)
        var pwdNever = hygiene?.PwdNeverExpire ?? 0;
        if (pwdNever == 0)
        {
            AppendIronCompliant(sb, "🧹", es ? "Higiene — contraseñas con expiración" : "Hygiene — password expiration", es);
        }
        else
        {
            sb.AppendLine("<div style='background:#FEF2F2;border:1px solid #FECACA;border-left:4px solid #991B1B;border-radius:4px;padding:10px 16px;margin-bottom:10px'>");
            sb.AppendLine($"<div style='font-size:11px;font-weight:700;color:#1E293B'>🧹 {HtmlEncode(es ? "Higiene — cuentas con Password Never Expires" : "Hygiene — Password Never Expires accounts")}</div>");
            sb.AppendLine($"<div style='font-size:10px;color:#7F1D1D;margin-top:4px'>{pwdNever} {HtmlEncode(es ? "cuentas" : "accounts")}</div>");
            sb.AppendLine("</div>");
        }

        // 6. Endpoint — Defender disabled
        var noDefender = allResults
            .Where(r => r.Status == "fail" && (
                r.Name.Contains("Defender", StringComparison.OrdinalIgnoreCase) ||
                r.Name.Contains("Antivirus", StringComparison.OrdinalIgnoreCase) ||
                r.Name.Contains("Real-Time Protection", StringComparison.OrdinalIgnoreCase) ||
                r.Name.Contains("AntiSpyware", StringComparison.OrdinalIgnoreCase)))
            .Select(r => runLookup.GetValueOrDefault(r.RunId, "unknown"))
            .Distinct()
            .ToList();
        AppendIronSection(sb, "🛡️", es ? "Endpoint — Defender deshabilitado" : "Endpoint — Defender disabled",
            noDefender, es);
    }

    public static void AppendIronSection(StringBuilder sb, string icon, string title, List<string> hostnames, bool es)
    {
        if (hostnames.Count == 0)
        {
            AppendIronCompliant(sb, icon, title, es);
            return;
        }
        sb.AppendLine("<div style='background:#FEF2F2;border:1px solid #FECACA;border-left:4px solid #991B1B;border-radius:4px;padding:10px 16px;margin-bottom:10px'>");
        sb.AppendLine($"<div style='font-size:11px;font-weight:700;color:#1E293B;margin-bottom:6px'>{icon} {HtmlEncode(title)} — {hostnames.Count} {HtmlEncode(es ? "equipos" : "machines")}</div>");
        sb.AppendLine($"<div style='font-size:9px;font-family:monospace;color:#7F1D1D;line-height:1.6'>{HtmlEncode(string.Join(" · ", hostnames.Take(40)))}");
        if (hostnames.Count > 40)
            sb.AppendLine($"<em> … {hostnames.Count - 40} {HtmlEncode(es ? "más" : "more")}</em>");
        sb.AppendLine("</div>");
        sb.AppendLine("</div>");
    }

    public static void AppendIronCompliant(StringBuilder sb, string icon, string title, bool es = false)
    {
        sb.AppendLine("<div style='background:#F0FDF4;border:1px solid #BBF7D0;border-left:4px solid #15803D;border-radius:4px;padding:8px 14px;margin-bottom:10px;font-size:10px;color:#166534'>");
        sb.AppendLine($"<strong>{icon} {HtmlEncode(title)}</strong> — ✅ {(es ? "Todos los equipos cumplen" : "All machines compliant")}");
        sb.AppendLine("</div>");
    }

    public static void AppendDataDrivenRecommendations(StringBuilder sb, List<AssessmentRun> runs,
        List<OrgControlResult> allResults, HygieneScanDto? hygiene, OrgEnrichment enrichment,
        ReportBranding brand)
    {
        var recommendations = new List<(string Priority, string Title, string Description, string Effort)>();
        var totalMachines = runs.Count;

        // AD hygiene recommendations
        if (hygiene != null)
        {
            var domainLevel = hygiene.Findings.FirstOrDefault(f => f.Status == "DomainLevel");
            if (domainLevel != null && (domainLevel.Detail?.Contains("2008") == true || domainLevel.Detail?.Contains("2003") == true))
                recommendations.Add(("Critical", "Upgrade Domain Functional Level",
                    $"Current level ({HtmlEncode(domainLevel.Detail ?? "outdated")}) prevents modern security features like Protected Users group and authentication silos.",
                    "1-2 weeks"));

            var lapsCount = hygiene.Findings.Count(f => f.Status == "NoLAPS");
            if (lapsCount > 0)
                recommendations.Add(("Critical", $"Deploy LAPS Across {hygiene.TotalMachines} Machines",
                    $"Currently {Math.Round(100.0 - (double)lapsCount / Math.Max(hygiene.TotalMachines, 1) * 100):F0}% coverage. LAPS prevents lateral movement by ensuring unique local admin passwords.",
                    "1-2 days"));

            if (hygiene.DormantMachines > 10)
                recommendations.Add(("High", $"Remove {hygiene.DormantMachines} Dormant Computer Objects",
                    "Orphaned computer accounts expand the attack surface and indicate poor lifecycle management.",
                    "1 day"));

            if (hygiene.PwdNeverExpire > 10)
                recommendations.Add(("High", $"Enforce Password Expiration for {hygiene.PwdNeverExpire} Accounts",
                    "Non-expiring passwords violate NIST, CIS, and HIPAA requirements.",
                    "1-2 days"));

            var privileged = hygiene.Findings.Count(f => f.Status == "Privileged");
            if (privileged > 10)
                recommendations.Add(("High", $"Review {privileged} Privileged Accounts",
                    "Excessive admin accounts increase the blast radius of credential compromise.",
                    "1-2 days"));
        }

        // Port-based recommendations
        var riskyPorts = enrichment.Ports.Where(p => p.Risk != null).ToList();
        var rdpCount = riskyPorts.Where(p => p.Port == 3389).Select(p => p.MachineId).Distinct().Count();
        if (rdpCount > 0)
            recommendations.Add(("Critical", $"Close or Restrict RDP on {rdpCount} Machines",
                "RDP is the leading ransomware attack vector. Implement VPN or RD Gateway instead of direct exposure.",
                "1-3 days"));

        // Threat-based recommendations
        if (enrichment.Threats.Count > 0)
            recommendations.Add(("Critical", $"Investigate {enrichment.Threats.Count} Threat Detections",
                $"Active threats detected across {enrichment.Threats.Select(t => t.MachineId).Distinct().Count()} devices. Immediate forensic analysis recommended.",
                "Immediate"));

        // Hardware recommendations
        var noBitlocker = runs.Count(r => r.Machine.Bitlocker != true);
        if (noBitlocker > 0)
            recommendations.Add(("Medium", $"Enable BitLocker on {noBitlocker} Devices",
                "Unencrypted drives expose data if devices are lost or stolen.",
                "1-2 days"));

        var noTpm = runs.Count(r => r.Machine.TpmPresent != true);
        if (noTpm > 0 && noTpm < totalMachines)
            recommendations.Add(("Medium", $"Enable TPM on {noTpm} Devices",
                "TPM enables hardware-backed security features including BitLocker and Windows Hello.",
                "Varies"));

        // Compliance-based recommendations
        var worstCategories = allResults
            .GroupBy(r => r.Category)
            .Select(g => new { Category = g.Key, Pct = g.Count() > 0 ? Math.Round((double)g.Count(x => x.Status == "pass") / g.Count() * 100) : 0 })
            .Where(x => x.Pct < 50)
            .OrderBy(x => x.Pct)
            .Take(3)
            .ToList();

        foreach (var cat in worstCategories)
        {
            recommendations.Add(("Medium", $"Harden {cat.Category} ({cat.Pct:F0}% compliance)",
                $"This category is significantly below target. Addressing these controls will have the highest impact on overall compliance.",
                "1-2 weeks"));
        }

        // Render recommendations table (top 10)
        sb.AppendLine("<table class='results-table'>");
        sb.AppendLine("<tr><th>#</th><th>Priority</th><th>Recommendation</th><th>Effort</th></tr>");
        var recNum = 1;
        foreach (var rec in recommendations.Take(10))
        {
            var sevClass = rec.Priority == "Critical" ? "critical" : rec.Priority == "High" ? "high" : "medium";
            var rowClass = rec.Priority == "Critical" ? "fail" : rec.Priority == "High" ? "warn" : "pass";
            sb.AppendLine($"<tr class='{rowClass}'>");
            sb.AppendLine($"<td class='num'>{recNum++}</td>");
            sb.AppendLine($"<td><span class='severity {sevClass}'>{HtmlEncode(rec.Priority)}</span></td>");
            sb.AppendLine($"<td><strong>{rec.Title}</strong><br><span style='font-size:11px;color:#666'>{rec.Description}</span></td>");
            sb.AppendLine($"<td>{HtmlEncode(rec.Effort)}</td>");
            sb.AppendLine("</tr>");
        }
        sb.AppendLine("</table>");
    }

    public static string HtmlEncode(string? value) =>
        System.Net.WebUtility.HtmlEncode(value ?? "");

    /// <summary>Minimal i18n. Returns English unless lang == "es" and a translation exists.</summary>
    public static string T(string key, string lang)
    {
        return lang == "es"
            ? (_esStrings.TryGetValue(key, out var es) ? es : (_enStrings.TryGetValue(key, out var en0) ? en0 : key))
            : (_enStrings.TryGetValue(key, out var en) ? en : key);
    }

    private static readonly Dictionary<string, string> _enStrings = new()
    {
        ["op.eyebrow"]             = "EXECUTIVE BRIEF",
        ["op.title"]               = "Security Posture — Executive Brief",
        ["op.header.subtitle"]     = "C-Level One-Page Summary",
        ["op.kpi.score"]           = "Overall score",
        ["op.kpi.grade"]           = "Grade",
        ["op.kpi.machines"]        = "Machines assessed",
        ["op.kpi.critical"]        = "Critical failures",
        ["op.frameworks"]          = "Framework compliance",
        ["op.frameworks.caption"]  = "P / F = average passing / failing controls per machine",
        ["op.risks"]               = "Top 3 risks",
        ["op.wins"]                = "Top 3 quick wins",
        ["op.no_risks"]            = "No critical or high-severity findings — the fleet is in good shape.",
        ["op.no_wins"]             = "No easy fixes pending — focus on the hardening roadmap.",
        ["op.remediation.label"]   = "Estimated remediation effort",
        ["op.remediation.hours"]   = "hours",
        ["op.remediation.note"]    = "Ballpark assumes related controls are bundled into a single GPO/Intune profile per category (e.g. all Edge hardening = 1 GPO) plus ~15 min of validation per endpoint. A sizing call produces the final quote.",
        ["op.footer.prepared"]     = "Prepared by",
        ["op.footer.generated"]    = "Generated",
        ["op.footer.confidential"] = "Confidential — For internal use of",
        ["op.risk.affects"]        = "affects",
        ["op.risk.machines"]       = "machines",
        ["op.risk.machine"]        = "machine",
        ["op.cover.for"]           = "Prepared for",
        ["op.cover.date"]          = "Assessment date",
        ["op.cover.score"]         = "Overall posture",
    };

    private static readonly Dictionary<string, string> _esStrings = new()
    {
        ["op.eyebrow"]             = "RESUMEN EJECUTIVO",
        ["op.title"]               = "Postura de Seguridad — Resumen Ejecutivo",
        ["op.header.subtitle"]     = "Resumen en una página para dirección",
        ["op.kpi.score"]           = "Puntaje global",
        ["op.kpi.grade"]           = "Calificación",
        ["op.kpi.machines"]        = "Equipos evaluados",
        ["op.kpi.critical"]        = "Fallos críticos",
        ["op.frameworks"]          = "Cumplimiento por framework",
        ["op.frameworks.caption"]  = "P / F = controles promedio que pasan / fallan por equipo",
        ["op.risks"]               = "Top 3 riesgos",
        ["op.wins"]                = "Top 3 acciones rápidas",
        ["op.no_risks"]            = "Sin hallazgos críticos ni altos — la flota está saludable.",
        ["op.no_wins"]             = "No hay correcciones rápidas pendientes — se recomienda avanzar con el plan de hardening.",
        ["op.remediation.label"]   = "Esfuerzo estimado de remediación",
        ["op.remediation.hours"]   = "horas",
        ["op.remediation.note"]    = "Estimación asumiendo que los controles relacionados se agrupan en una GPO/perfil Intune por categoría (ej: todo el hardening de Edge = 1 GPO) más ~15 min de validación por endpoint. Una reunión de dimensionamiento da el número final.",
        ["op.footer.prepared"]     = "Preparado por",
        ["op.footer.generated"]    = "Generado",
        ["op.footer.confidential"] = "Confidencial — Uso interno de",
        ["op.risk.affects"]        = "afecta a",
        ["op.risk.machines"]       = "equipos",
        ["op.risk.machine"]        = "equipo",
        ["op.cover.for"]           = "Preparado para",
        ["op.cover.date"]          = "Fecha de evaluación",
        ["op.cover.score"]         = "Postura general",
    };
}
