namespace KryossApi.Services.CopilotReadiness;

public enum ServiceCategory
{
    Entra,
    Defender,
    Purview,
    M365,
    PowerPlatform,
    CopilotStudio
}

public static class ServicePlanMapping
{
    private static readonly Dictionary<string, ServiceCategory> _map =
        new(StringComparer.OrdinalIgnoreCase)
        {
            // Entra (14)
            { "AAD_PREMIUM",                            ServiceCategory.Entra },
            { "AAD_PREMIUM_P2",                         ServiceCategory.Entra },
            { "AAD_PREMIUM_CONDITIONAL_ACCESS",         ServiceCategory.Entra },
            { "AAD_PREMIUM_IDENTITY_PROTECTION",        ServiceCategory.Entra },
            { "AAD_PREMIUM_P1",                         ServiceCategory.Entra },
            { "AAD_GOVERNANCE",                         ServiceCategory.Entra },
            { "MFA_PREMIUM",                            ServiceCategory.Entra },
            { "INTUNE_A",                               ServiceCategory.Entra },
            { "ENTRA_INTERNET_ACCESS",                  ServiceCategory.Entra },
            { "ENTRA_INTERNET_ACCESS_FRONTLINE",        ServiceCategory.Entra },
            { "ENTRA_PRIVATE_ACCESS",                   ServiceCategory.Entra },
            { "ENTRA_PRIVATE_ACCESS_CA",                ServiceCategory.Entra },

            // Defender (17)
            { "WINDEFATP",                              ServiceCategory.Defender },
            { "ATP_ENTERPRISE",                         ServiceCategory.Defender },
            { "MTP",                                    ServiceCategory.Defender },
            { "ATA",                                    ServiceCategory.Defender },
            { "ADALLOM_S_DISCOVERY",                    ServiceCategory.Defender },
            { "ADALLOM_S_O365",                         ServiceCategory.Defender },
            { "ADALLOM_S_STANDALONE",                   ServiceCategory.Defender },
            { "EOP_ENTERPRISE_PREMIUM",                 ServiceCategory.Defender },
            { "SAFEDOCS",                               ServiceCategory.Defender },
            { "THREAT_INTELLIGENCE",                    ServiceCategory.Defender },
            { "DEFENDER_FOR_IOT",                       ServiceCategory.Defender },
            { "Defender_for_Iot_Enterprise",            ServiceCategory.Defender },

            // Purview (36)
            { "AIP_P1",                                         ServiceCategory.Purview },
            { "AIP_P2",                                         ServiceCategory.Purview },
            { "COMMUNICATIONS_COMPLIANCE",                      ServiceCategory.Purview },
            { "COMMUNICATIONS_DLP",                             ServiceCategory.Purview },
            { "ContentExplorer_Standard",                       ServiceCategory.Purview },
            { "CONTENTEXPLORER_STANDARD_ACTIVITY",              ServiceCategory.Purview },
            { "Content_Explorer",                               ServiceCategory.Purview },
            { "CustomerLockboxA_Enterprise",                    ServiceCategory.Purview },
            { "CUSTOMER_KEY",                                   ServiceCategory.Purview },
            { "DATAINVESTIGATION",                              ServiceCategory.Purview },
            { "DATA_INVESTIGATIONS",                            ServiceCategory.Purview },
            { "EDISCOVERY",                                     ServiceCategory.Purview },
            { "EQUIVIO_ANALYTICS",                              ServiceCategory.Purview },
            { "EQUIVIO_ANALYTICS_EDM",                          ServiceCategory.Purview },
            { "INFORMATION_BARRIERS",                           ServiceCategory.Purview },
            { "INFORMATION_PROTECTION_ANALYTICS",               ServiceCategory.Purview },
            { "INFORMATION_PROTECTION_COMPLIANCE_PREMIUM",      ServiceCategory.Purview },
            { "INFO_GOVERNANCE",                                ServiceCategory.Purview },
            { "INSIDER_RISK",                                   ServiceCategory.Purview },
            { "INSIDER_RISK_MANAGEMENT",                        ServiceCategory.Purview },
            { "LOCKBOX_ENTERPRISE",                             ServiceCategory.Purview },
            { "M365_ADVANCED_AUDITING",                         ServiceCategory.Purview },
            { "M365_AUDIT_PLATFORM",                            ServiceCategory.Purview },
            { "MICROSOFTENDPOINTDLP",                           ServiceCategory.Purview },
            { "MICROSOFT_COMMUNICATION_COMPLIANCE",             ServiceCategory.Purview },
            { "MIP_S_CLP1",                                     ServiceCategory.Purview },
            { "MIP_S_CLP2",                                     ServiceCategory.Purview },
            { "MIP_S_Exchange",                                 ServiceCategory.Purview },
            { "ML_CLASSIFICATION",                              ServiceCategory.Purview },
            { "PAM_ENTERPRISE",                                 ServiceCategory.Purview },
            { "PREMIUM_ENCRYPTION",                             ServiceCategory.Purview },
            { "PURVIEW_DISCOVERY",                              ServiceCategory.Purview },
            { "RECORDS_MANAGEMENT",                             ServiceCategory.Purview },
            { "RMS_S_ENTERPRISE",                               ServiceCategory.Purview },
            { "RMS_S_PREMIUM",                                  ServiceCategory.Purview },
            { "RMS_S_PREMIUM2",                                 ServiceCategory.Purview },

            // M365 (85+)
            { "EXCHANGE_S_ENTERPRISE",                          ServiceCategory.M365 },
            { "EXCHANGE_S_STANDARD",                            ServiceCategory.M365 },
            { "EXCHANGE_S_FOUNDATION",                          ServiceCategory.M365 },
            { "EXCHANGE_S_DESKLESS",                            ServiceCategory.M365 },
            { "EXCHANGE_S_ARCHIVE_ADDON",                       ServiceCategory.M365 },
            { "EXCHANGE_ANALYTICS",                             ServiceCategory.M365 },
            { "EXCHANGEDESKLESS",                               ServiceCategory.M365 },
            { "EXCHANGEDESKLESS_GOV",                           ServiceCategory.M365 },
            { "TEAMS1",                                         ServiceCategory.M365 },
            { "TEAMSPRO_CUST",                                  ServiceCategory.M365 },
            { "TEAMSPRO_MGMT",                                  ServiceCategory.M365 },
            { "TEAMSPRO_PROTECTION",                            ServiceCategory.M365 },
            { "TEAMSPRO_VIRTUALAPPT",                           ServiceCategory.M365 },
            { "TEAMSPRO_WEBINAR",                               ServiceCategory.M365 },
            { "TEAMS_PREMIUM_CUSTOMER",                         ServiceCategory.M365 },
            { "SHAREPOINTENTERPRISE",                           ServiceCategory.M365 },
            { "SHAREPOINTSTANDARD",                             ServiceCategory.M365 },
            { "SHAREPOINTWAC",                                  ServiceCategory.M365 },
            { "ONEDRIVE_BASIC_P2",                              ServiceCategory.M365 },
            { "OFFICESUBSCRIPTION",                             ServiceCategory.M365 },
            { "OFFICEMOBILE_SUBSCRIPTION",                      ServiceCategory.M365 },
            { "M365_COPILOT_APPS",                              ServiceCategory.M365 },
            { "M365_COPILOT_BUSINESS_CHAT",                     ServiceCategory.M365 },
            { "M365_COPILOT_CONNECTORS",                        ServiceCategory.M365 },
            { "M365_COPILOT_INTELLIGENT_SEARCH",                ServiceCategory.M365 },
            { "M365_COPILOT_SHAREPOINT",                        ServiceCategory.M365 },
            { "M365_COPILOT_TEAMS",                             ServiceCategory.M365 },
            { "GRAPH_CONNECTORS_COPILOT",                       ServiceCategory.M365 },
            { "GRAPH_CONNECTORS_SEARCH_INDEX",                  ServiceCategory.M365 },
            { "Bing_Chat_Enterprise",                           ServiceCategory.M365 },
            { "MICROSOFT_LOOP",                                 ServiceCategory.M365 },
            { "MICROSOFT_SEARCH",                               ServiceCategory.M365 },
            { "CLIPCHAMP",                                      ServiceCategory.M365 },
            { "SWAY",                                           ServiceCategory.M365 },
            { "FORMS_PLAN_E1",                                  ServiceCategory.M365 },
            { "FORMS_PLAN_E5",                                  ServiceCategory.M365 },
            { "BPOS_S_TODO_3",                                  ServiceCategory.M365 },
            { "PROJECTWORKMANAGEMENT",                          ServiceCategory.M365 },
            { "PROJECTWORKMANAGEMENT_PLANNER",                  ServiceCategory.M365 },
            { "PROJECT_O365_P1",                                ServiceCategory.M365 },
            { "PROJECT_O365_P3",                                ServiceCategory.M365 },
            { "DESKLESS",                                       ServiceCategory.M365 },
            { "EXCEL_PREMIUM",                                  ServiceCategory.M365 },
            { "MICROSOFTBOOKINGS",                              ServiceCategory.M365 },
            { "MICROSOFT_ECDN",                                 ServiceCategory.M365 },
            { "MICROSOFT_MYANALYTICS_FULL",                     ServiceCategory.M365 },
            { "MICROSOFT_PLACES",                               ServiceCategory.M365 },
            { "INSIGHTS_BY_MYANALYTICS",                        ServiceCategory.M365 },
            { "MYANALYTICS_P1",                                 ServiceCategory.M365 },
            { "MYANALYTICS_P2",                                 ServiceCategory.M365 },
            { "MYANALYTICS_P3",                                 ServiceCategory.M365 },
            { "NUCLEUS",                                        ServiceCategory.M365 },
            { "PEOPLE_SKILLS_FOUNDATION",                       ServiceCategory.M365 },
            { "PLACES_CORE",                                    ServiceCategory.M365 },
            { "PLACES_ENHANCED",                                ServiceCategory.M365 },
            { "QUEUES_APP",                                     ServiceCategory.M365 },
            { "STREAM_O365_E5",                                 ServiceCategory.M365 },
            { "UNIVERSAL_PRINT_01",                             ServiceCategory.M365 },
            { "VIVAENGAGE_CORE",                                ServiceCategory.M365 },
            { "VIVA_GOALS",                                     ServiceCategory.M365 },
            { "VIVA_INSIGHTS_BACKEND",                          ServiceCategory.M365 },
            { "VIVA_INSIGHTS_MYANALYTICS_FULL",                 ServiceCategory.M365 },
            { "VIVA_LEARNING_SEEDED",                           ServiceCategory.M365 },
            { "WHITEBOARD_PLAN3",                               ServiceCategory.M365 },
            { "WIN10_PRO_ENT_SUB",                              ServiceCategory.M365 },
            { "WIN10_VDA_E3",                                   ServiceCategory.M365 },
            { "WINDOWSUPDATEFORBUSINESS_DEPLOYMENTSERVICE",     ServiceCategory.M365 },
            { "WINDOWS_AUTOPATCH",                              ServiceCategory.M365 },
            { "WORKPLACE_ANALYTICS_INSIGHTS_BACKEND",           ServiceCategory.M365 },
            { "WORKPLACE_ANALYTICS_INSIGHTS_USER",              ServiceCategory.M365 },
            { "YAMMER_ENTERPRISE",                              ServiceCategory.M365 },
            { "MCOEV",                                          ServiceCategory.M365 },
            { "MCOEV_VIRTUALUSER",                              ServiceCategory.M365 },
            { "MCOIMP",                                         ServiceCategory.M365 },
            { "MCOMEETADV",                                     ServiceCategory.M365 },
            { "MCOSTANDARD",                                    ServiceCategory.M365 },
            { "MCOSTANDARD_GOV",                                ServiceCategory.M365 },
            { "MCO_VIRTUAL_APPT",                               ServiceCategory.M365 },
            { "MCO_VIRTUAL_APPT_PREMIUM",                       ServiceCategory.M365 },
            { "MESH",                                           ServiceCategory.M365 },
            { "MESH_AVATARS_ADDITIONAL_FOR_TEAMS",              ServiceCategory.M365 },
            { "MESH_AVATARS_FOR_TEAMS",                         ServiceCategory.M365 },
            { "MESH_IMMERSIVE",                                 ServiceCategory.M365 },
            { "MESH_IMMERSIVE_FOR_TEAMS",                       ServiceCategory.M365 },
            { "INTUNE_O365",                                    ServiceCategory.M365 },
            { "INTUNE_SUITE",                                   ServiceCategory.M365 },
            { "KAIZALA_STANDALONE",                             ServiceCategory.M365 },
            { "M365_LIGHTHOUSE_CUSTOMER_PLAN1",                 ServiceCategory.M365 },
            { "TEAMWORK_ANALYTICS",                             ServiceCategory.M365 },

            // Power Platform (17)
            { "FLOW_O365_P3",           ServiceCategory.PowerPlatform },
            { "FLOW_FREE",              ServiceCategory.PowerPlatform },
            { "FLOW_P2_VIRAL",          ServiceCategory.PowerPlatform },
            { "FLOW_CCI_BOTS",          ServiceCategory.PowerPlatform },
            { "POWERAPPS_O365_P3",      ServiceCategory.PowerPlatform },
            { "CDS_O365_P1",            ServiceCategory.PowerPlatform },
            { "CDS_O365_P2",            ServiceCategory.PowerPlatform },
            { "CDS_O365_P3",            ServiceCategory.PowerPlatform },
            { "CDS_VIRAL",              ServiceCategory.PowerPlatform },
            { "DYN365_CDS_O365_P1",     ServiceCategory.PowerPlatform },
            { "DYN365_CDS_O365_P2",     ServiceCategory.PowerPlatform },
            { "DYN365_CDS_O365_P3",     ServiceCategory.PowerPlatform },
            { "DYN365_CDS_VIRAL",       ServiceCategory.PowerPlatform },
            { "DYN365_CDS_CCI_BOTS",    ServiceCategory.PowerPlatform },
            { "BI_AZURE_P2",            ServiceCategory.PowerPlatform },

            // Copilot Studio (11)
            { "POWER_VIRTUAL_AGENTS",                       ServiceCategory.CopilotStudio },
            { "POWER_VIRTUAL_AGENTS_BASE",                  ServiceCategory.CopilotStudio },
            { "POWER_VIRTUAL_AGENTS_O365_P3",               ServiceCategory.CopilotStudio },
            { "CDS_VIRTUAL_AGENT_BASE_MESSAGES",            ServiceCategory.CopilotStudio },
            { "CDS_VIRTUAL_AGENT_USL",                      ServiceCategory.CopilotStudio },
            { "COPILOT_STUDIO_IN_COPILOT_FOR_M365",         ServiceCategory.CopilotStudio },
            { "FLOW_VIRTUAL_AGENT_BASE_MESSAGES",           ServiceCategory.CopilotStudio },
            { "FLOW_VIRTUAL_AGENT_USL",                     ServiceCategory.CopilotStudio },
            { "VIRTUAL_AGENT_BASE_MESSAGES",                ServiceCategory.CopilotStudio },
            { "VIRTUAL_AGENT_USL",                          ServiceCategory.CopilotStudio },
            { "CCIBOTS_PRIVPREV_VIRAL",                     ServiceCategory.CopilotStudio },
        };

    public static IReadOnlyDictionary<string, ServiceCategory> All => _map;

    public static ServiceCategory? Classify(string servicePlanName)
    {
        if (string.IsNullOrWhiteSpace(servicePlanName)) return null;
        return _map.TryGetValue(servicePlanName, out var category) ? category : null;
    }
}
