using System.Text.Json.Serialization;

namespace KryossAgent.Models;

/// <summary>
/// Source-generated JSON serializer context for AOT compatibility.
/// All types that need serialization/deserialization must be listed here.
/// </summary>
[JsonSerializable(typeof(AssessmentPayload))]
[JsonSerializable(typeof(AgentEnvelope))]
[JsonSerializable(typeof(EnrollRequest))]
[JsonSerializable(typeof(ControlsResponse))]
[JsonSerializable(typeof(EnrollmentResponse))]
[JsonSerializable(typeof(ResultsResponse))]
[JsonSerializable(typeof(CheckResult))]
[JsonSerializable(typeof(List<CheckResult>))]
[JsonSerializable(typeof(ControlDef))]
[JsonSerializable(typeof(List<ControlDef>))]
[JsonSerializable(typeof(PlatformInfo))]
[JsonSerializable(typeof(HardwareInfo))]
[JsonSerializable(typeof(DiskInfo))]
[JsonSerializable(typeof(List<DiskInfo>))]
[JsonSerializable(typeof(SoftwareItem))]
[JsonSerializable(typeof(List<SoftwareItem>))]
[JsonSerializable(typeof(ThreatFinding))]
[JsonSerializable(typeof(List<ThreatFinding>))]
[JsonSerializable(typeof(NetworkDiagResult))]
[JsonSerializable(typeof(LatencyResult))]
[JsonSerializable(typeof(List<LatencyResult>))]
[JsonSerializable(typeof(RouteEntry))]
[JsonSerializable(typeof(List<RouteEntry>))]
[JsonSerializable(typeof(VpnInterface))]
[JsonSerializable(typeof(List<VpnInterface>))]
[JsonSerializable(typeof(AdapterInfo))]
[JsonSerializable(typeof(List<AdapterInfo>))]
[JsonSerializable(typeof(BandwidthInfo))]
[JsonSerializable(typeof(TracerouteHop))]
[JsonSerializable(typeof(List<TracerouteHop>))]
[JsonSerializable(typeof(CloudEndpointLatency))]
[JsonSerializable(typeof(List<CloudEndpointLatency>))]
[JsonSerializable(typeof(SnmpCredentials))]
[JsonSerializable(typeof(SnmpScanResult))]
[JsonSerializable(typeof(SnmpDeviceResult))]
[JsonSerializable(typeof(List<SnmpDeviceResult>))]
[JsonSerializable(typeof(SnmpInterfaceResult))]
[JsonSerializable(typeof(SnmpEntityInfo))]
[JsonSerializable(typeof(LldpNeighbor))]
[JsonSerializable(typeof(List<LldpNeighbor>))]
[JsonSerializable(typeof(CdpNeighbor))]
[JsonSerializable(typeof(List<CdpNeighbor>))]
[JsonSerializable(typeof(PrinterSupply))]
[JsonSerializable(typeof(List<PrinterSupply>))]
[JsonSerializable(typeof(SnmpHostResources))]
[JsonSerializable(typeof(SnmpStorageEntry))]
[JsonSerializable(typeof(List<SnmpStorageEntry>))]
[JsonSerializable(typeof(SnmpProfilesResponse))]
[JsonSerializable(typeof(SnmpVendorProfile))]
[JsonSerializable(typeof(List<SnmpVendorProfile>))]
[JsonSerializable(typeof(SnmpProfileOidEntry))]
[JsonSerializable(typeof(List<SnmpProfileOidEntry>))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(OfflineCollectPayload))]
[JsonSerializable(typeof(List<OfflineCollectPayload>))]
[JsonSerializable(typeof(HygienePayload))]
[JsonSerializable(typeof(HygieneFinding))]
[JsonSerializable(typeof(List<HygieneFinding>))]
[JsonSerializable(typeof(PortPayload))]
[JsonSerializable(typeof(PortBulkPayload))]
[JsonSerializable(typeof(PortEntry))]
[JsonSerializable(typeof(List<PortEntry>))]
// Primitive types that can appear polymorphically inside CheckResult.Value (object?).
// Without these, source-gen throws NotSupportedException when an engine writes a
// boxed long/int/bool/string/double to Value (e.g. EventLogConfiguration.MaximumSizeInBytes
// returns long, TpmEngine.Present returns bool, etc.).
[JsonSerializable(typeof(long))]
[JsonSerializable(typeof(int))]
[JsonSerializable(typeof(bool))]
[JsonSerializable(typeof(string))]
[JsonSerializable(typeof(double))]
[JsonSerializable(typeof(LocalAdminItem))]
[JsonSerializable(typeof(List<LocalAdminItem>))]
[JsonSerializable(typeof(PatchStatusInfo))]
[JsonSerializable(typeof(HotfixItem))]
[JsonSerializable(typeof(List<HotfixItem>))]
[JsonSerializable(typeof(DcHealthPayload))]
[JsonSerializable(typeof(DcReplPartner))]
[JsonSerializable(typeof(List<DcReplPartner>))]
[JsonSerializable(typeof(HeartbeatPayload))]
[JsonSerializable(typeof(HeartbeatResponse))]
[JsonSerializable(typeof(AgentRemoteConfig))]
[JsonSerializable(typeof(PendingRemediationTask))]
[JsonSerializable(typeof(List<PendingRemediationTask>))]
[JsonSerializable(typeof(TaskResultPayload))]
[JsonSerializable(typeof(ScheduleResponse))]
[JsonSourceGenerationOptions(
    PropertyNameCaseInsensitive = true,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
public partial class KryossJsonContext : JsonSerializerContext
{
}
