SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO
-- =============================================
-- 005_enrollment_crypto.sql
-- Kryoss Platform — Agent Enrollment + Per-Org Crypto Keys
-- Depends on: 002_core.sql (organizations), 003_cmdb.sql (machines),
--             004_assessment.sql (assessments)
-- =============================================

-- =============================================
-- ENROLLMENT_CODES: One-time use, expirable, pre-assigned to assessment
-- Generated by admin/franchisee in the portal, consumed by agent on first run
-- =============================================
CREATE TABLE enrollment_codes (
    id              INT IDENTITY(1,1) PRIMARY KEY,
    organization_id UNIQUEIDENTIFIER NOT NULL REFERENCES organizations(id),
    code            VARCHAR(32)    NOT NULL UNIQUE,    -- random 32-char alphanumeric
    assessment_id   INT            REFERENCES assessments(id),
    label           NVARCHAR(255),                     -- "Oficina central", "Laptop Juan"
    used_by         UNIQUEIDENTIFIER REFERENCES machines(id),  -- NULL until used
    used_at         DATETIME2(2),
    expires_at      DATETIME2(2)   NOT NULL,           -- default: 7 days from creation
    -- Audit columns
    created_by      UNIQUEIDENTIFIER NOT NULL,
    created_at      DATETIME2(2)   NOT NULL DEFAULT SYSUTCDATETIME(),
    modified_by     UNIQUEIDENTIFIER,
    modified_at     DATETIME2(2),
    deleted_by      UNIQUEIDENTIFIER,
    deleted_at      DATETIME2(2)
);

CREATE INDEX ix_enrollment_available ON enrollment_codes(code) WHERE used_by IS NULL AND deleted_at IS NULL;
CREATE INDEX ix_enrollment_org       ON enrollment_codes(organization_id) WHERE deleted_at IS NULL;

-- =============================================
-- ORG_CRYPTO_KEYS: RSA key pairs per organization
-- Public key stored here, private key in Azure Key Vault
-- Used for encrypting agent payloads in transit
-- =============================================
CREATE TABLE org_crypto_keys (
    id              INT IDENTITY(1,1) PRIMARY KEY,
    organization_id UNIQUEIDENTIFIER NOT NULL REFERENCES organizations(id),
    public_key_pem  NVARCHAR(MAX)  NOT NULL,           -- RSA-2048 public key in PEM format
    key_vault_ref   NVARCHAR(255)  NOT NULL,           -- Azure Key Vault secret URI for private key
    fingerprint     VARCHAR(64)    NOT NULL,            -- SHA-256 of public key for matching
    is_active       BIT            NOT NULL DEFAULT 1,
    -- Audit columns
    created_by      UNIQUEIDENTIFIER NOT NULL,
    created_at      DATETIME2(2)   NOT NULL DEFAULT SYSUTCDATETIME(),
    modified_by     UNIQUEIDENTIFIER,
    modified_at     DATETIME2(2),
    deleted_by      UNIQUEIDENTIFIER,
    deleted_at      DATETIME2(2)
);

-- Key rotation tracking
ALTER TABLE org_crypto_keys ADD rotated_at DATETIME2(2) NULL;

-- Only one active key per org
CREATE UNIQUE INDEX ux_orgkeys_active ON org_crypto_keys(organization_id) WHERE is_active = 1 AND deleted_at IS NULL;
