SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO
-- =============================================
-- 012_billing.sql
-- Kryoss Platform — Billing: Subscriptions, Invoices, Commissions
-- Hybrid model: Kryoss calculates everything, pushes to Odoo for fiscal invoicing
-- Depends on: 002_core.sql (franchises, organizations), 010_crm.sql (service_catalog, currencies)
-- =============================================

-- =============================================
-- CLIENT_SUBSCRIPTIONS: Active plans/services per client
-- What each organization is paying for monthly
-- =============================================
CREATE TABLE client_subscriptions (
    id              UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    organization_id UNIQUEIDENTIFIER NOT NULL REFERENCES organizations(id),
    service_id      INT            NOT NULL REFERENCES service_catalog(id),
    -- Pricing
    quantity        DECIMAL(10,2)  NOT NULL DEFAULT 1,  -- number of devices/users/licenses
    unit_price      DECIMAL(12,2)  NOT NULL,
    currency_id     INT            NOT NULL REFERENCES currencies(id),
    discount_pct    DECIMAL(5,2)   NOT NULL DEFAULT 0,
    line_total      AS (quantity * unit_price * (1 - discount_pct / 100)) PERSISTED,
    -- Billing cycle
    billing_cycle   VARCHAR(10)    NOT NULL DEFAULT 'monthly'
        CONSTRAINT ck_sub_cycle CHECK (billing_cycle IN ('monthly', 'quarterly', 'annual')),
    start_date      DATE           NOT NULL,
    end_date        DATE,                               -- NULL = ongoing
    next_billing    DATE           NOT NULL,
    -- Status
    status          VARCHAR(20)    NOT NULL DEFAULT 'active'
        CONSTRAINT ck_sub_status CHECK (status IN ('active', 'paused', 'cancelled', 'expired')),
    -- Audit columns
    created_by      UNIQUEIDENTIFIER NOT NULL,
    created_at      DATETIME2(2)   NOT NULL DEFAULT SYSUTCDATETIME(),
    modified_by     UNIQUEIDENTIFIER,
    modified_at     DATETIME2(2),
    deleted_by      UNIQUEIDENTIFIER,
    deleted_at      DATETIME2(2)
);

CREATE INDEX ix_subs_org    ON client_subscriptions(organization_id) WHERE status = 'active' AND deleted_at IS NULL;
CREATE INDEX ix_subs_billing ON client_subscriptions(next_billing) WHERE status = 'active' AND deleted_at IS NULL;

-- =============================================
-- INVOICES: Generated by Kryoss, pushed to Odoo
-- =============================================
CREATE TABLE invoices (
    id              UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    franchise_id    UNIQUEIDENTIFIER NOT NULL REFERENCES franchises(id),
    organization_id UNIQUEIDENTIFIER NOT NULL REFERENCES organizations(id),
    -- Invoice identity
    invoice_number  NVARCHAR(50)   NOT NULL,            -- "INV-2026-0001"
    -- Period
    period_start    DATE           NOT NULL,
    period_end      DATE           NOT NULL,
    -- Amounts
    subtotal        DECIMAL(12,2)  NOT NULL DEFAULT 0,
    tax_rate        DECIMAL(5,2)   NOT NULL DEFAULT 0,  -- e.g. 21% IVA
    tax_amount      DECIMAL(12,2)  NOT NULL DEFAULT 0,
    total           DECIMAL(12,2)  NOT NULL DEFAULT 0,
    currency_id     INT            NOT NULL REFERENCES currencies(id),
    -- Status
    status          VARCHAR(20)    NOT NULL DEFAULT 'draft'
        CONSTRAINT ck_inv_status CHECK (status IN ('draft', 'sent', 'paid', 'overdue', 'cancelled', 'credited')),
    due_date        DATE,
    paid_at         DATETIME2(2),
    -- Odoo sync
    odoo_invoice_id NVARCHAR(100),                     -- Odoo reference after push
    odoo_synced_at  DATETIME2(2),
    -- Notes
    notes           NVARCHAR(MAX),
    -- Audit columns
    created_by      UNIQUEIDENTIFIER NOT NULL,
    created_at      DATETIME2(2)   NOT NULL DEFAULT SYSUTCDATETIME(),
    modified_by     UNIQUEIDENTIFIER,
    modified_at     DATETIME2(2),
    deleted_by      UNIQUEIDENTIFIER,
    deleted_at      DATETIME2(2)
);

CREATE UNIQUE INDEX ux_invoice_number ON invoices(franchise_id, invoice_number) WHERE deleted_at IS NULL;
CREATE INDEX ix_invoices_org    ON invoices(organization_id) WHERE deleted_at IS NULL;
CREATE INDEX ix_invoices_status ON invoices(franchise_id, status) WHERE deleted_at IS NULL;
CREATE INDEX ix_invoices_overdue ON invoices(due_date) WHERE status = 'sent' AND deleted_at IS NULL;

-- =============================================
-- INVOICE_ITEMS: Line items in an invoice
-- From subscriptions + billable time entries + custom items
-- =============================================
CREATE TABLE invoice_items (
    id              INT IDENTITY(1,1) PRIMARY KEY,
    invoice_id      UNIQUEIDENTIFIER NOT NULL REFERENCES invoices(id),
    -- Source reference
    subscription_id UNIQUEIDENTIFIER REFERENCES client_subscriptions(id),
    time_entry_id   UNIQUEIDENTIFIER REFERENCES ticket_time_entries(id),
    service_id      INT            REFERENCES service_catalog(id),
    -- Line item
    description     NVARCHAR(500)  NOT NULL,
    quantity        DECIMAL(10,2)  NOT NULL DEFAULT 1,
    unit_price      DECIMAL(12,2)  NOT NULL,
    discount_pct    DECIMAL(5,2)   NOT NULL DEFAULT 0,
    line_total      AS (quantity * unit_price * (1 - discount_pct / 100)) PERSISTED,
    sort_order      SMALLINT       NOT NULL DEFAULT 0
);

CREATE INDEX ix_invitems_invoice ON invoice_items(invoice_id);

-- =============================================
-- COMMISSION_PERIODS: Monthly commission calculation per franchise
-- 15% (or configured %) on net billing from franchisee's clients
-- =============================================
CREATE TABLE commission_periods (
    id              UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    franchise_id    UNIQUEIDENTIFIER NOT NULL REFERENCES franchises(id),
    year_month      CHAR(7)        NOT NULL,            -- '2026-04'
    currency_id     INT            NOT NULL REFERENCES currencies(id),
    -- Revenue
    gross_revenue   DECIMAL(14,2)  NOT NULL DEFAULT 0,  -- total invoiced by franchise's clients
    net_revenue     DECIMAL(14,2)  NOT NULL DEFAULT 0,  -- after discounts/credits
    -- Commission
    commission_pct  DECIMAL(5,2)   NOT NULL DEFAULT 15.00,
    commission_amount DECIMAL(14,2) NOT NULL DEFAULT 0, -- net_revenue * commission_pct / 100
    -- Status
    status          VARCHAR(20)    NOT NULL DEFAULT 'pending'
        CONSTRAINT ck_comm_status CHECK (status IN ('pending', 'calculated', 'approved', 'released', 'paid')),
    approved_by     UNIQUEIDENTIFIER REFERENCES users(id),
    approved_at     DATETIME2(2),
    released_at     DATETIME2(2),
    paid_at         DATETIME2(2),
    -- Odoo sync
    odoo_ref        NVARCHAR(100),
    odoo_synced_at  DATETIME2(2),
    -- Audit columns
    created_by      UNIQUEIDENTIFIER NOT NULL,
    created_at      DATETIME2(2)   NOT NULL DEFAULT SYSUTCDATETIME(),
    modified_by     UNIQUEIDENTIFIER,
    modified_at     DATETIME2(2),
    deleted_by      UNIQUEIDENTIFIER,
    deleted_at      DATETIME2(2)
);

CREATE UNIQUE INDEX ux_commission_period ON commission_periods(franchise_id, year_month) WHERE deleted_at IS NULL;
CREATE INDEX ix_commission_status ON commission_periods(status) WHERE deleted_at IS NULL;

-- =============================================
-- PAYMENT_HISTORY: Track payments received
-- =============================================
CREATE TABLE payments (
    id              UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    invoice_id      UNIQUEIDENTIFIER NOT NULL REFERENCES invoices(id),
    amount          DECIMAL(12,2)  NOT NULL,
    currency_id     INT            NOT NULL REFERENCES currencies(id),
    payment_method  VARCHAR(30)    NOT NULL DEFAULT 'transfer'
        CONSTRAINT ck_payment_method CHECK (payment_method IN ('transfer', 'credit_card', 'debit', 'cash', 'check', 'crypto', 'other')),
    payment_date    DATE           NOT NULL,
    reference       NVARCHAR(255),                     -- bank ref, transaction ID
    notes           NVARCHAR(500),
    -- Audit columns
    created_by      UNIQUEIDENTIFIER NOT NULL,
    created_at      DATETIME2(2)   NOT NULL DEFAULT SYSUTCDATETIME(),
    modified_by     UNIQUEIDENTIFIER,
    modified_at     DATETIME2(2),
    deleted_by      UNIQUEIDENTIFIER,
    deleted_at      DATETIME2(2)
);

CREATE INDEX ix_payments_invoice ON payments(invoice_id) WHERE deleted_at IS NULL;
